name: dynamic_form_builder_example
description: Example app for dynamic_form_builder package
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_form_builder:
    path: ../
  flex_color_picker: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 