name: json_form_builder
description: A Flutter package for building dynamic forms from JSON data with multi-language support.
version: 0.0.2
homepage: https://github.com/moradchalaby/json_form_builder
repository: https://github.com/moradchalaby/json_form_builder

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  path: ^1.8.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flex_color_picker: ^3.7.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  generate: true
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:
